[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ml_platform"
version = "0.1.10"
authors = [
  { name="Tung HOANG", email="author@example.com" },
]
description = "ML Platform"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [ 
]
